'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GSCOM.Applications.InSys.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        Friend ReadOnly Property _report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_report", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property BlueBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueBall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property CloseButtoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseButtoImage", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property Collapsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapsed", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property Expanded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Expanded", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property FormRun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormRun", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property GreenBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenBall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
        Friend ReadOnly Property hands() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hands", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
        Friend ReadOnly Property InSysBlueAbout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InSysBlueAbout", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property Menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property Properties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Properties", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property RedBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedBall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;yNd5vuGvSDusOVQMFNUOWNHFPxuvCQXZ393AqK/m/Suzt7zyGoAxFdXgp0n375v/Y16zL4wBmVGxbHf4lFuHAl7+FoFEFhfIGZ3v9ULuJUxwf+7G5blNdfjzPmG70mDQZT630VZWLXKbp5tffzmA99cRCs2vIpBAG5TsryMptuM=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;7W06kma1xeYqtIB3wAP2UjAVlkg5Pc78JKMQpRFspLVeUHUnX6EFk+6XPtqedIvTUU8Rwu/LK6qB3WV3xgybNQ==&lt;/P&gt;&lt;Q&gt;2I2WDQpERT6RqPVP0oNH8kETyOGJfaqD0gYb2ZzRsx0mI/2BLQoyWNedB1o6zfvpuR+OJo+sq462QIwxciA0tw==&lt;/Q&gt;&lt;DP&gt;k4B3kfqDVTYgM9FYFA+iGP9MeffWsAKGfRBdR9+iWlVfCacu1edIetYQWnkhVhCEMRBpXWzyEOe2FGB0X7L3PQ==&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RSAKeyValue() As String
            Get
                Return ResourceManager.GetString("RSAKeyValue", resourceCulture)
            End Get
        End Property

        Friend ReadOnly Property servers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("servers", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property VSProject_database() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VSProject_database", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Friend ReadOnly Property YellowBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowBall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
